export const mockData = [
  {
    rank: 1,
    name: "Ron",
    calmmer_ratio: 3.4,
    overall_profit: 22334,
    daily_porfit: 343432,
    win_percent: 56,
    price: 78,
    action: "View",
  },
  {
    rank: 2,
    name: "helle",
    calmmer_ratio: 3.14,
    overall_profit: 234234,
    daily_porfit: 32423423,
    win_percent: 34,
    price: 23,
    action: "View",
  },
  {
    rank: 3,
    name: "Vin",
    calmmer_ratio: 2.89,
    overall_profit: 785556,
    daily_porfit: 56767,
    win_percent: 12,
    price: 56,
    action: "Buy",
  },
  {
    rank: 4,
    name: "Goat",
    calmmer_ratio: 4.78,
    overall_profit: 434323,
    daily_porfit: 4563,
    win_percent: 11,
    price: "-",
    action: "Buy",
  },
  {
    rank: 5,
    name: "Rina",
    calmmer_ratio: 6.89,
    overall_profit: 32983,
    daily_porfit: 128645,
    win_percent: 90,
    price: "-",
    action: "View",
  },
  {
    rank: 6,
    name: "You",
    calmmer_ratio: 5.89,
    overall_profit: 2398945,
    daily_porfit: 17435,
    win_percent: 34,
    price: 675,
    action: "View",
  },
  {
    rank: 7,
    name: "Sev",
    calmmer_ratio: 3.56,
    overall_profit: 233418,
    daily_porfit: 90674,
    win_percent: 13,
    price: "-",
    action: "View",
  },
  {
    rank: 8,
    name: "Feoll",
    calmmer_ratio: 7.14,
    overall_profit: 34967,
    daily_porfit: 1232,
    win_percent: 65,
    price: 67,
    action: "Buy",
  },
  {
    rank: 9,
    name: "Ben",
    calmmer_ratio: 5.0,
    overall_profit: 452,
    daily_porfit: 2341,
    win_percent: 32,
    price: 56,
    action: "Buy",
  },
  {
    rank: 10,
    name: "Tenison",
    calmmer_ratio: 6.78,
    overall_profit: 23454,
    daily_porfit: 2343,
    win_percent: 12,
    price: 23,
    action: "Buy",
  },
];

export const header = [
  {
    icon: "SiWindows11",
    headers: "LeaderBoard",
  },
  {
    icon: "SiWindows11",
    headers: "Historical Trading",
  },
  {
    headers: "Historical Chart",
  },
  {
    headers: "Scanners",
  },
  {
    headers: "Alerts",
  },
  {
    headers: "Basic Backtest",
  },
  {
    headers: "Advance Backtest",
  },
  {
    headers: "Pricing",
  },
  {
    headers: "My Earnings",
  },
];
